### ISSUE TITLE
Bug report: Add warp point requires answering: `remove /var/folders/d7/...?`

### ISSUE THREAD

**Issue by mikestopcontinues** [mfaerevaag/wd#100]
**Describe the bug**
When I run something like `wd add <key>`, I'm asked to answer the following:

`remove /var/folders/d7/lzqxykg13nj607z1jnxxtjzr0000gn/T//wd.[HASH]?`

It works whether I answer Y or N. I'm not sure when this bug creeped in, but its from the version packaged with OMZ.

**To Reproduce**
1. `wd add <key>`
2. See `remove /var/folders/d7/lzqxykg13nj607z1jnxxtjzr0000gn/T//wd.[HASH]?`
3. Y or N allows it to continue.

**Expected behavior**
I expect it to ask me nothing.

**Desktop (please complete the following information):**
 - zsh version: 5.7.1 (x86_64-apple-darwin19.0)
 - wd version: 0.5.0

**Comment by alpha-tango-kilo** [comment]
I'm guessing you have an alais for `rm` in your config that makes it interactive by default?

If you confirm this, I can patch this nice and easily

**Comment by mikestopcontinues** [comment]
Whoa, it turns out I do have such an alias, though I didn't create it. Turns out it's the OMZ common-aliases plugin. I'm not sure why it only started happening now, though I haven't created any new warp points in quite a while. I'd very much appreciate a patch, but if you consider it outside scope, I'll just disable the plugin.

https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/common-aliases/common-aliases.plugin.zsh

Thanks!

**Comment by alpha-tango-kilo** [comment]
Issue solved in latest commit to master and v0.5.1

I've opened a PR on ohmyzsh to get this sorted updated there for you too: https://github.com/ohmyzsh/ohmyzsh/pull/9273

**Comment by mikestopcontinues** [comment]
Thanks a million!
