### ISSUE TITLE
Idea: wd - to jump back to previous warp directory

### ISSUE THREAD

**Issue by johannesschweig** [mfaerevaag/wd#119]
I find myself often jumping between two warp directories. It would be nice if I could just to `wd -` to jump back to the previous one similar to how `cd -` works.

**Comment by alpha-tango-kilo** [comment]
Can you do `wd cool-place` and then `cd -` back? If so, do we need this in wd?

This shouldn't be too difficult to implement though. We'd just need to store the previous directory before each warp (either in the rc file, an environment variable, or some `/tmp` file), then disallow `-` being a warp name when creating a warp, and then have `wd -` take you back to the previous place

I'm not going to implement it myself I'm afraid - I'm very passively maintaining `wd` and not actually currently using it, however I'd happily review a PR and answer what questions I can if that would help you do it!

**Comment by johannesschweig** [comment]
`cd -` works. I never considered that. That's actually a good enough solution for me.

**Comment by alpha-tango-kilo** [comment]
Sometimes the simple solution works best 😄 Thanks for confirming! Under the hood `wd` just ends up calling `cd` so it makes sense that this would work
