### ISSUE TITLE
Bug report: history expansion command is empty when pressing enter

### ISSUE THREAD

**Issue by mcornella** [mfaerevaag/wd#126]
**Describe the bug**

History expansion sequences (`!` plus a history descriptor, e.g. `!!` or `!<num>`) are getting ignored when trying to run them.

**To Reproduce**
1. Use version 0.6.2 or newer.
2. Run a command, for example `date`.
3. Type `!!` and press enter. A new command line is drawn, with an empty command.

**Expected behavior**
The previous command should be run or a new command prompt line should be created with the text of the previous command, depending on whether `setopt histverify` is enabled or not.

**Screenshots**
See https://github.com/ohmyzsh/ohmyzsh/issues/12489.

**Desktop (please complete the following information):**
 - zsh version: 5.9
 - wd version: 0.7.0

**Additional context**

This is caused by #122, given that `wd_restore_buffer` will delete `$BUFFER` if `$saved_buffer` is empty.

**Comment by p1r473** [comment]
Let me look into this

**Comment by p1r473** [comment]
Good find! Fixed in https://github.com/mfaerevaag/wd/pull/127
