### ISSUE TITLE
Bug report: oh-my-zsh wd plugin binds C-b

### ISSUE THREAD

**Issue by Schmoho** [mfaerevaag/wd#131]
**Describe the bug**
Pressing C-b activates a menu to choose from warp points.

**To Reproduce**
Steps to reproduce the behavior: (on endeavouros)
1. install zsh 
2. install oh-my-zsh
3. activate wd plugin
4. press C-b

**Expected behavior**
Don't bind C-b. As an Emacs user I cannot work around this. Have I done something stupid that I don't remember? Is this configurable somehow? If not, it would be really nice if it were, or could be mapped to a different key.

**Desktop (please complete the following information):**
 - zsh version: 5.9
 - wd version: 0.7.0

**Comment by Schmoho** [comment]
Okay sorry, I was so outraged I forgot to rtfm

Sure there is other ways, but `bindkey ${FZF_WD_BINDKEY:-'^B'} backward-char`  after plugin init overrides the behaviour.

**Comment by alpha-tango-kilo** [comment]
Yeah the binding comes from https://github.com/mfaerevaag/wd/blob/759cd29828108a70d58b784059552da8333087c8/wd.plugin.zsh#L21

If you can think of a good way to make this more configurable, or improve our documentation, I'd happily review a PR
