### ISSUE TITLE
Idea: consider changing the ctrl-b key 

### ISSUE THREAD

**Issue by altschuler** [mfaerevaag/wd#133]
Hi,

I see that the ctrl-b binding has come up a few times now, and I just wanted to chime in with an opinion :)

In short, I don’t think that “taking” the ctrl-b shortcut is a good idea. It’s too fundamental a binding for anyone using emacs layout in their terminal (which I suppose is the majority of zsh users, but I don’t know). I was frustrated when that menu started popping up, and I had no idea why it did so or even what it was to begin with. I didn’t notice that it was after an omz update, and I can only suspect many other users would have a similar experience.

Was there a rationale behind that key in particular or could it be changed to something else? 

Thank you for your great maintenance work on this project @alpha-tango-kilo! ❤️

**Comment by alpha-tango-kilo** [comment]
Yeah I agree, I think the default should be removed or changed to something more obscure, based on the issue reports and PRs we've been getting. I didn't know Ctrl + B was a thing people did in their terminals when I originally accepted the PR

Would be happy to merge a PR that removes/changes this bind, ideally with documentation on how to configure it to their liking

**Comment by alpha-tango-kilo** [comment]
Fixed in #134, released in v0.8.0 (bumping the major version as this is a breaking change)

I believe oh-my-zsh is configured to be updated automatically on release, so this should hit users soon!
