### ISSUE TITLE
Bug report: Path to the `/bin/zsh` interpreter might not be found

### ISSUE THREAD

**Issue by zimeg** [mfaerevaag/wd#135]
**Describe the bug**

Calling the `wd.sh` script directly might cause an exit with error if the path to `zsh` doesn't match `/bin/zsh`.

**To reproduce**

1. Change the $PATH of `zsh`
2. Invoke the powerful `wd.sh` script ✨ 
3. Hope for the best

**Expected behavior**

The script to find `zsh` with the `env` program:

```
$ cat ./wd.sh
#!/usr/bin/env zsh
...
$ ./wd.sh --version
wd version 0.8.0
```

**Current behavior**

The installed `zsh` might not be found:

```
$ which zsh
/home/user/.nix-profile/bin/zsh
$ ./wd.sh --version
zsh: ./wd.sh: bad interpreter: /bin/zsh: no such file or directory
```

**Desktop**

 - zsh version: zsh 5.9 (x86_64-pc-linux-gnu)
 - wd version: 0.8.0

**Additional context**

I'm noticing that installing `wd` as a **plugin** seems to avoid this issue for me, which is super interesting! Perhaps some magic is happening with path management? 🪄  I haven't explored this too much, but found that swapping with `env` can be a fix for the direct call to `wd.sh` 🤔

This doesn't seem to be related to recent changes as far as I can tell either. I just noticed this with some recent test runs 🔬 It all continues to warp so well for me 👁️‍🗨️

I'm also unsure if using `/bin/zsh` is expected for plugins - please let me know if this is just fine as is! 🙏

**Comment by alpha-tango-kilo** [comment]
Thanks for writing up such a detailed issue! I would happily accept a PR changing the shebang of all the wd scripts to `#!/usr/bin/env zsh`. I don't see why that'd cause issues (given the whole point of that more verbose shebang is to be more portable), and Nix(OS) seems to be gaining traction in the Linux community from what little an eye I have on it so I think it'd be good to make sure wd can work well there too!

**Comment by zimeg** [comment]
@alpha-tango-kilo It's fun to explore the strangeness, thanks a ton for the fast response! I sent the PR #136 that changes most of the files (tests and the actual scripts) but please let me know if any of this needs changing! 🙏

And super interesting to hear about more words of Nix too 👀 Even with weird quirks like this, it's continued to impress me so much! I hope to continue sharing more good words of it with **some** subtlety haha  ❄️ ✨
