### ISSUE TITLE
Bug report: Using the `--config` flag changes the `WD_CONFIG` environment variable

### ISSUE THREAD

**Issue by zimeg** [mfaerevaag/wd#140]
**Describe the bug**

The `WD_CONFIG` environment variable is changed after using the `--config` flag.

**To reproduce**

1. List outputs from the current `WD_CONFIG` value. This could be using a default that might have a few points included:

```zsh
$ echo $WD_CONFIG
/home/user/.warprc
$ cat $WD_CONFIG
...
$ wd list
...
```

2. List points from a configuration that might not exist. This might list nothing:

```zsh
$ wd --config /tmp/points list
...
```

3. Attempt to list points from the earlier `WD_CONFIG` value without using a flag:

```zsh
$ wd list
...
$ echo $WD_CONFIG
/tmp/points
```

**Current behavior**

The last commands lists values from flagged `--config` options from a previous command.

**Expected behavior**

The last commands to list the values from the initial `WD_CONFIG` variable since no flag is provided.

**Desktop**

- zsh version: `5.9`
- wd version: `0.9.1`

**Additional context**

I'm unsure if this should be an issue or if this flag is meant to change the `WD_CONFIG` value overall. Though no problem closing this if it's expected!

**Comment by alpha-tango-kilo** [comment]
Fix released as v0.9.2, thanks!
