### ISSUE TITLE
Bug report: The exit code remains `0` if a nested directory does not exist

### ISSUE THREAD

**Issue by zimeg** [mfaerevaag/wd#142]
**Describe the bug**

The exit code remains `0` if the nested directory of a warp point doesn't exit and the current path remains the same.

In this example the `setup.sh` script is run when it can't be found in the current directory:

```zsh
$ wd home unknown && ./setup.sh
wd_warp:cd:18: no such file or directory: /home/user/unknown
zsh: no such file or directory: ./setup.sh
```

**To reproduce**

1. Attempt to warp to unknown nested warp points:

```zsh
$ cd
$ wd add home
$ wd home unknown
wd_warp:cd:18: no such file or directory: /home/user/unknown
$ echo $?
0
$ pwd
/home/user
```

**Expected behavior**

The exit code to exit with an error code if the nested directory doesn't exit to skip following steps in chained commands:

```zsh
$ wd home unknown && ./setup.sh
wd_warp:cd:18: no such file or directory: /home/user/unknown
```

**Desktop**

- zsh version: `5.9`
- wd version: `0.9.1`

**Comment by alpha-tango-kilo** [comment]
Fix released as v0.9.2, thanks!
