### ISSUE TITLE
Ability to go to sub dir from warp point

### ISSUE THREAD

**Issue by altschuler** [mfaerevaag/wd#17]
Let's say we have a tree like

```
foo
├── bar
│   └── baz
├── file.txt
└── qux
```

and a warp point `f` pointing at the `foo` directory. Then it'd be sweet to be able to directly do

```
wd f/bar/baz
```

or 

```
wd f/qux
```

and be warped to `baz` and `qux` respectively.

Another feature would be to edit a file using the `$EDITOR` env variable so we could do something like

```
wd -e f/file.txt
```

Or even just automagically edit if the target is a file.

And of course we would need autocompletion of subdirs for this to be awesome :)

**Comment by creynders** [comment]
👍

**Comment by mfaerevaag** [comment]
@altschuler What do you know

**Comment by altschuler** [comment]
Please check [this branch](https://github.com/mfaerevaag/wd/tree/subdir) and let me know if there are any issues with it. It needs some testing, but otherwise it seems to work fine.

Instead of typing the slash as in the description of this issue you simply type the subdir after the warp points name, so using the above example:

```
wd f <tab>
```

results in regular path completion (only directories) for the `foo` directory. Using the space makes it easier to use than writing `/`because you can just double `<tab>` to get the completion.

**Comment by avently** [comment]
@mfaerevaag @altschuler for me this doesn't work. I have the latest version: 0.4.2.
```
cd ~/.config

wd add config
* Warp point added

wd list
* All warp points:
config  ->  ~/.config

ls | grep htop
htop

cd  ~

wd config htop
 
pwd
/home/avently/.config
```

Am i doing something wrong?

**Comment by mfaerevaag** [comment]
@avently 

Hm, that's odd. Could you paste `zsh --version`, please?

**Comment by altschuler** [comment]
@avently just checking; is `htop` a directory?

**Comment by avently** [comment]
@mfaerevaag zsh 5.4.2 (x86_64-unknown-linux-gnu)

**Comment by mfaerevaag** [comment]
@altschuler Guess the first step is to reproduce bug. So maybe some unit tests which should pass, and get @avently to run them? I at least, can't reproduce this on my machine.

**Comment by avently** [comment]
@mfaerevaag, i found the cause of this issue. I use oh-my-zsh and you didn't update your zsh branch to this commit... So i have the same version as you but without that commit.

**Comment by altschuler** [comment]
Nice detective work! :)

It's worth noting that you need a space after the warp point when auto completing directories, so `wd config<space><tab>` should work, but `wd config<tab>` won't.

**Comment by avently** [comment]
@altschuler oh, _wd.sh is also changed. I have renewed wd.sh only before your message. With new _wd.sh it works fine. Thank you for your help, guys!

**Comment by avently** [comment]
@altschuler it is a little bit odd but autocompletion only works with paths not containing ~. 
For example, ~/.config will not work.   /home/avently/.config will work. Can you confirm or it's again my fault?
So, if i go to ~/.config and add warp point to that path, .warprc will contain  config:~/.config. And autocompletion will not work until i change path in .warprc to config:/home/avently/.config

**Comment by mfaerevaag** [comment]
Good call. I've forgotten to update the oh-my-zsh plugin. Submitted PR [#6371](https://github.com/robbyrussell/oh-my-zsh/pull/6371). This does not include your last suggestion though, which I think be tested a little more before submitting.

@altschuler Do you have problems with paths including '~' in your `.warprc`? My zsh auto-completion is messed up in general, so don't really trust it.

**Comment by altschuler** [comment]
That does indeed seem to be the problem! Adding `val=${val/~/$HOME}` does not seem to work for me though, what is it supposed to do?

**Comment by avently** [comment]
@altschuler it should replace ~ sign from .warprc with the path to your home dir /home/yourname. It only replace in real-time when you want to query all subdirectories of warp point. 
wd something <tab>
So, if you have a point like ~/.config with this fix you should get /home/yourname/.config.

Are you sure you pasted this line in an appropriate place? After initial declaration of `val`

**Comment by avently** [comment]
@altschuler sorry, markdown ruins the command.
Before ~ you should paste backslash

`val=${val/\~/$HOME}`

**Comment by altschuler** [comment]
Ah now it works! I guess that expression is replacing the first occurrence of `~` with `$HOME`, right? If I have a point in my warprc like `foo:~/tmp/~foo` it works fine, but `foo:/home/simon/tmp/~foo` breaks, which I assume is because the dirs name `~foo` is being expanded to `/home/simonfoo`. 

Any way we can replace it only if it's the beginning of the path? Maybe zsh has a function for this?

**Comment by avently** [comment]
@altschuler looks not good but works 
` [[ ${val:0:1} == "~" ]] && val=$HOME${val:1}`

**Comment by mfaerevaag** [comment]
According to `man zshall`, line 2044, in the "Variable Expansion" section:

 > The  pattern  may begin with a `#', in which case the pattern must match at the start of the string

So for me, this works
```zsh
➜ ~  foo="~/tmp/~foo"
➜ ~  echo ${foo/#\~/$HOME}
/home/markus/tmp/~foo
```

**Comment by avently** [comment]
Cool. That works too. 
So, the final answer is
`val=${val/#\~/$HOME}`

**Comment by altschuler** [comment]
Sweet! Would you like to do a PR @avently?

**Comment by avently** [comment]
@altschuler no:)

**Comment by mfaerevaag** [comment]
Maybe with little comment so we remember the reason? We've fixed to many zsh 'gotchas', so I'm starting to lose track 😩

**Comment by altschuler** [comment]
Haha, honesty is a virtue! We'll take care of it. Thank you very much for your help! :)

**Comment by mfaerevaag** [comment]
Yep, thanks @avently ! 🤘

**Comment by avently** [comment]
@mfaerevaag you forgot to update oh-my-zsh branch:)

**Comment by mfaerevaag** [comment]
@avently https://github.com/mfaerevaag/wd/blob/oh-my-zsh/_wd.sh#L26-L27

Maybe you didn't notice, as I merged it into the bump commit I made just before.

**Comment by avently** [comment]
@mfaerevaag yes, now i see

**Comment by mzanibelli** [comment]
Hi. Thanks for this very useful plugin. There seems to be a critical problem with the fix as it overrides `$PATH` which is case-insensitive. I think the variable needs to be scoped with the use of `local`. Does anyone have the same problem ?

**Comment by altschuler** [comment]
@mzanibelli Thanks! I've pushed a quickfix, just renaming the variable. We'll @mfaerevaag to do the magic of releasing to oh-my-zsh :)

**Comment by mzanibelli** [comment]
Excellent ! You definitely got it faster :1st_place_medal: I was writing the fix. Thanks

**Comment by mfaerevaag** [comment]
That was quick! Bumped to v0.4.5 and submitted [PR #6383](https://github.com/robbyrussell/oh-my-zsh/pull/6383) to oh-my-zsh 👍

**Comment by mzanibelli** [comment]
Oh. And now I'm actually reading it : we forgot to replace an occurrence inside the curly brackets on line 27.

**Comment by altschuler** [comment]
Woops, I'm going a bit too quick here, didn't see your PR before I pushed that. Shame on me for not testing... Thanks for the review <3

**Comment by mzanibelli** [comment]
Well i'm slowly learning how to use Github so don't wait for me ! Keep in mind it won't be noticeable if people only `wd` to `/usr/bin` until it's merged ;)
