### ISSUE TITLE
Better describe wd 

### ISSUE THREAD

**Issue by mfaerevaag** [mfaerevaag/wd#18]
The README should do a better job of reflecting what `wd` actually accomplishes, and what the difference is from `oh-my-zsh` plugins like [autojump](https://github.com/joelthelion/autojump) and [z](https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/z).

**Comment by LazerPanther** [comment]
A .gif of your console showing wd in use could be very helpful.

**Comment by mfaerevaag** [comment]
Great idea! Will look at this when we get some freetime

**Comment by mfaerevaag** [comment]
Ok, so got tired of looking at these issues, so as @LazerPanther suggested, I'm making a gif!

Any comments on what should be included in the gif? @altschuler For example:
```bash
cd some/very/long/path
cd some/other/long/path
echo "ain't got time for this zshiet"
clear
cd some/very/long/path
wd add foo
cd some/other/long/path
wd add bar
cd ~
wd foo
echo $pwd
wd bar
echo $pwd
```

**Comment by altschuler** [comment]
I would show `wd list` because it looks nice. Also I would merge https://github.com/mfaerevaag/wd/pull/45 and show that :P

**Comment by sindrenm** [comment]
I feel the tab completion is worth showing too:

```bash
cd ~/projects/personal/open-source/secret-mountain-api
wd add
wd sec<TAB> # expanded to secret-mountain-api
```

**Comment by mfaerevaag** [comment]
@altschuler forgotten that you have merge privileges? 😏 

Alright, so something like
```bash
cd dev/code/shell
ls
wd add sh
cd ~

wd ls sh

wd <tab> -> sh wd
wd add

wd list
```

**Comment by mfaerevaag** [comment]
Didn`t get the new feature as my environment is a little messed up. How about this one:
![tty](https://cloud.githubusercontent.com/assets/1221244/24703414/1a4655e0-1a3e-11e7-9335-5cd473c2e167.gif)

**Comment by mfaerevaag** [comment]
Btw, this was made with [icholy/ttygif](https://github.com/icholy/ttygif). Give it a try and we'll post the best one 🥇

**Comment by mfaerevaag** [comment]
I've pushed the one I made above til someone makes a better one. I'm too busy/lazy to do it again and this issue was hurting my OCD 🙊
