### ISSUE TITLE
Relative warp paths

### ISSUE THREAD

**Issue by GeraintCorneu** [mfaerevaag/wd#31]
Hi, thanks for this script, you've saved me a lot of time! :)

Is there any functionality for using relative paths? I'd like my .warprc to be portable on my various devices through git.

**Comment by mfaerevaag** [comment]
Sorry for the late reply!

Agreed! Portability between different devices should be fixed. I'm surprised this has not been noticed before. Thanks for that:)

**Comment by mfaerevaag** [comment]
Should now be supported, thanks to @hiberabyss
