### ISSUE TITLE
Upgrade version

### ISSUE THREAD

**Issue by sindrenm** [mfaerevaag/wd#34]
It feels a bit strange to make an issue for this, but I realized that there are [quite a few changes] made between the most recent version (0.4.1) and master.

Would it be possible to release a new version? It would be really helpful for those of us that gets the plugin through oh-my-zsh, since it looks like oh-my-zsh only updates its plugins when there are new versions released.

Thanks. :smile: 

[quite a few changes]: https://github.com/mfaerevaag/wd/compare/v0.4.1...master

**Comment by mfaerevaag** [comment]
You are absolutely right, there should be a new version shiped out to oh-my-zsh. Thanks for pointing that out :+1: 

I've asked the oh-my-zsh guys to [merge the new stuff](https://github.com/robbyrussell/oh-my-zsh/pull/4634).

There is also a new release of wd, here this repo, namely [v0.4.2](https://github.com/mfaerevaag/wd/releases/tag/v0.4.2).

**Comment by sindrenm** [comment]
You're my hero, @mfaerevaag, thanks a bunch! :smile:
