### ISSUE TITLE
wd ..

### ISSUE THREAD

**Issue by BenSapiens** [mfaerevaag/wd#36]
When I use the command "wd ..", which should access the "cd -n" (n number of steps back) functionality as described in the readme, I receive the following error.

wd_warp:6: no such file or directory: 2

I pulled a fresh copy of .oh-my-zsh, so I'm fairly certain it isn't a problem on my end. Let me know if you need any more information.

**Comment by mfaerevaag** [comment]
Very sorry for my late reply. I am currently using my time trailing the mountains of Norway, and will therefore not have time to check on it in the near future. Will check back asap!

**Comment by BenSapiens** [comment]
No worries. Enjoy.

**Comment by fgsch** [comment]
I think the issue here is the comparison.
This works for me:

```
diff --git a/plugins/wd/wd.sh b/plugins/wd/wd.sh
index cf54713..40b190b 100755
--- a/plugins/wd/wd.sh
+++ b/plugins/wd/wd.sh
@@ -134,7 +134,7 @@ wd_warp()
 
     if [[ $point =~ "^\.+$" ]]
     then
-        if [ $#1 < 2 ]
+        if [[ $#1 < 2 ]]
         then
             wd_exit_warn "Warping to current directory?"
         else
```

**Comment by mfaerevaag** [comment]
Had completely forgotten this! Is this still an issue? (Or has it magically disappeared?)

**Comment by fgsch** [comment]
Still needed afaict.

**Comment by BenSapiens** [comment]
It's still an issue. However, fgsch's simple bracket addition works great.

**Comment by ErsafanRend** [comment]
For me a similar error(?) occurs after I fire up a fresh zsh:
```
❯ wd ..
wd_warp:cd:12: no such entry in dir stack
```
After first use of `wd` it doesn't occur any more. 
So this doesn't bug me. Just wanted to let you know.

Using:
* zsh 5.4.2
* wd 0.4.6
* oh-my-zsh e273cf004e1ff0510aee614168850

**Comment by mfaerevaag** [comment]
Ah yes, this is due to directory stack being empty. The dir stack i a `zsh` feature (see `OLDPATH` in `man cd`.

Doing `wd ..` is the same as `cd -1 > /dev/null`. Essentially is pops the last `PWD` of an internal stack prints it and `cd`s to it.

So I guess the behavior is correct, but the error message is not too descriptive.. Maybe it should be improved. @sindrenm @altschuler Comments?
