### ISSUE TITLE
`wd` not complaining when passed multiple warp points

### ISSUE THREAD

**Issue by lschumm** [mfaerevaag/wd#42]
The Issue
=======

Suppose we have two warp points set, `test1 -> ~/Desktop` and `test2 -> /dev`. If the command

```
wd test1 test2
```

is run, then the directory is changed to `test2` without any further information. `wd` should say something like

```
 * Multiple warp points provided. Please provide only one warp point to wd.
```

(change to your liking)

Info
===

zsh 5.2 (x86_64-apple-darwin16.0). MacOS Sierra 10.12.1 (16B2657). MacBookAir7,1. ZSH selected from Terminal -> Preferences -> General -> Shells open with -> Command (complete path): /bin/zsh

**Comment by altschuler** [comment]
This will be redundant with https://github.com/mfaerevaag/wd/issues/17. With this feature `wd test1 test2` would warp to `<path_to_test1>/test2`.
