### ISSUE TITLE
'wd add' should allow elided argument

### ISSUE THREAD

**Issue by raxod502** [mfaerevaag/wd#44]
One of my more frequent actions with `wd` is:

```
$ cd my-repo
$ wd add my-repo
```

Wouldn't it be great if `wd add` defaulted to the current directory name?

```
$ cd my-repo
$ wd add
```

**Comment by sindrenm** [comment]
This is also one of my most common things to do with `wd`. Personally I've created an alias for doing just that, but I suppose it would be nice with a default, if it's not confusing to the user.

In case you're interested in a temporary solution, here's my simple alias:

```
alias wda='wd --add $(basename $PWD)'
```

**Comment by mfaerevaag** [comment]
Agreed. I think giving the add command the default value of `basename $PWD` is a fine. 

@altschuler comments?

**Comment by altschuler** [comment]
Sounds good to me :+1: Should we also provide pwd as deafult for `rm` then? Might cause some unwanted deletion, but it does give some consistency.

**Comment by Cretezy** [comment]
I had already made a pull request for exactly this. There's a fork in my profile with the implemented code

**Comment by Cretezy** [comment]
https://github.com/mfaerevaag/wd/pull/40

**Comment by mfaerevaag** [comment]
@Cretezy has indeed already done this! 🚀 Opened PR again

**Comment by mfaerevaag** [comment]
As pull-request needed some work I made a the [feature-add/rm-default-cwd](https://github.com/mfaerevaag/wd/tree/feature-add/rm-default-to-cwd) feature branch from #40, rebased, squashed and removed invalid tests. There is still three tests failing, which shouldn't, so something's wrong.

Get back to it this weekend.

```
test_empty_config
test_simple_add_remove
ASSERT:wps should be empty expected:<0> but was:<1>
test_no_duplicates
test_valid_identifiers
test_removal
ASSERT:should remove existing point
test_list
test_show
test_quiet
test_clean
ASSERT:should remove one warp point when using force
test_ls
test_path

Ran 11 tests.

FAILED (failures=3)
```

**Comment by sindrenm** [comment]
Haven't had much time in front of my computer as of late, so I haven't been able to test, but I'm sure you guys have this all under control. 😃

Great stuff! ❤️
