### ISSUE TITLE
Doesn't work when the path contains /

### ISSUE THREAD

**Issue by x-ji** [mfaerevaag/wd#49]
I'm on Mac OS 10.13. I have a directory named `Tuebingen17/18WS`. In the shell it seems to be represented as `Tuebingen17:18WS` instead. While I can `cd` to the directory, I can't successfully use `wd` on it. `wd add 1718` works without problems, but `wd 1718` results in `wd_warp:cd:15: no such file or directory: /Users/jx/Dropbox/Tuebingen17`. Apparently, `wd` failed to supply to `cd` the directory name after the `/` (`:`).

**Comment by altschuler** [comment]
That's a good point, we're not escaping directory names. When you say "in the shell" do you mean in the `.warprc` file?

**Comment by mfaerevaag** [comment]
Assuming your `.warprc`, looks something like
```
1718:Tuebingen17:18WS
```

This has something to do with how OS X handles slashes in file names. AFAIK, at a file system level (exFAT), it is not possible. Though in Finder you can, but really the forward slash is replaced by a colon and only displayed as a slash. I might be wrong!

Anyways, when we split each line in `.warprc` on colon, the line, in your case, would be three different strings, and as you mention, the last part (`18WS`) gets omitted.

Guess we could do something like this, when we load the warp points:
```diff
diff --git a/wd.sh b/wd.sh
index e7c869d..8fb796a 100755
--- a/wd.sh
+++ b/wd.sh
@@ -372,7 +372,7 @@ while read -r line
 do
     arr=(${(s,:,)line})
     key=${arr[1]}
-    val=${arr[2]}
+    val=${(j,:,)arr[2,-1]}
 
     points[$key]=$val
 done < $WD_CONFIG
```

Which seems to work me:
```zsh
➜ ~  mkdir Tuebingen17:18WS  
➜ ~  cd Tuebingen17:18WS 
➜ ~/Tuebingen17:18WS  wd add 1718
 * Warp point added
➜ ~/Tuebingen17:18WS  cd ..
➜ ~  wd 1718
➜ ~/Tuebingen17:18WS  pwd
/home/markus/Tuebingen17:18WS
```

Check out the [fix/path-with-colon](https://github.com/mfaerevaag/wd/tree/fix/path-with-colon) branch and see it does it.

**Comment by x-ji** [comment]
Thanks, that branch works.

**Comment by mfaerevaag** [comment]
Good to hear! Thanks for reporting 👍

**Comment by mfaerevaag** [comment]
Bumped to `v0.4.4` and added to our standing [PR #6371](https://github.com/robbyrussell/oh-my-zsh/pull/6371) to oh-my-zsh.
