### ISSUE TITLE
Add support for custom .warprc location

### ISSUE THREAD

**Issue by Shrvi** [mfaerevaag/wd#52]
Thank you for your amazing work.

I think it would be nice if the user could specify the location of the .warprc file.
There is the `--config` option and one could create an alias, but it breaks the completion of wd.

The easiest working way (I tested that) is, to set `WD_CONFIG` only if it is unset.
Also use `WD_CONFIG` instead of `CONFIG` in __wd_ to match.

This way user can specify `WD_CONFIG` to their wishes.

I thought of semthing like this `WD_CONFIG=${WD_CONFIG:-$HOME/.warprc}`.

**Comment by mfaerevaag** [comment]
That is very good idea! Hadn't thought of that the `--config` option would break completion.

I would be happy to merge this is if you have working fork and would make a pull request 😇 If not I'll get on this as soon I get some free time 👍

**Comment by mfaerevaag** [comment]
Thanks for this! 👍
