### ISSUE TITLE
wd should do "wd list" by default [VOTE HERE]

### ISSUE THREAD

**Issue by partounian** [mfaerevaag/wd#54]
Thoughts on wd to do wd list by default instead of the help message?

Vote here please: 👍 or 👎

**Comment by mfaerevaag** [comment]
I personally don't use `wd list` that much, but that doesn't mean it should be done. I think the users of wd should decide, so maybe it's possible to do a vote? Votes could be counted 👍  or 👎  on your issue. What do you think?

**Comment by mfaerevaag** [comment]
What do you think @altschuler @sindrenm ? Not sure how to get people to vote though. Could various people who has contributed, for instance.

**Comment by partounian** [comment]
Hey @mfaerevaag , thank you for the reply and leaving it up to the community! I have updated my OP with your voting instructutions. Tagging contributors/other known users is a great idea.

(note: I simply tagged everyone on the contributors page)
@malthejorgensen @hiberabyss @Shrvi @raxod502 @jceb @sindrenm @Cretezy @mrxinu @ruipacheco @kyokley @okiyama @maryokhin @martnu @sergey-kucher @hamiltont

**Comment by mrxinu** [comment]
I agree a default behavior like this makes a lot of sense. Because laziness. 😄

**Comment by raxod502** [comment]
I'm voting against this simply because I think `wd list` is not a very common operation and the easier it is to get a usage message, the better.

**Comment by mrxinu** [comment]
I'm with @raxod502 on this one. Changing my vote. Like a lemming. I look to things git as sort of the gold standard for command line applications and it behaves the same way - no arguments/flags = usage.

**Comment by partounian** [comment]
I used z as the motivation since it lists by default.

**Comment by partounian** [comment]
Noticing that it does not like list wd list default will win, does anyone have an idea why this causes a broken pipe and crash? The if conditions causes the terminal to crash immediately while the else half causes the broken pipe then crash.

Using oh-my-zsh, and macOS.
oh-my-zsh e273cf0
wd version 0.4.6
zsh 5.4.2

```
wd() {
  if [ $# -ge 1 ]; then
    wd "$@"
  else
    wd list
  fi
}
```

**Comment by Shrvi** [comment]
@partounian It's an infinite loop.
Maybe to late, but try this:
```sh
wdlist() {
  if [ $# -ge 1 ]; then
    wd "$@"
  else
    wd list
  fi
}
alias wd=wdlist
```
For zsh I recommend using `(( $# >= 1 ))` instead of `[ $# -ge 1 ]`

**Comment by partounian** [comment]
It is never too late to help on an issue!
Thank you @Shrvi it works perfectly. (Note for others: I used the zsh variant)
