### ISSUE TITLE
got error when warp point is also a command

### ISSUE THREAD

**Issue by zxeoc** [mfaerevaag/wd#56]
Hi, thanks for the great tool.

But I got error when using it recently. This is the situation. I am recently learning docker, so I put my dockerfiles in "/somewhere/docker" directory. Then I "wd add" it, surely this added a warp point "docker". Till this everything works fine.
But sometimes, when I run "wd docker" to warp to the path, zsh shows these:

> Command 'getopt' is available in '/usr/bin/getopt'
> The command could not be located because '/usr/bin' is not included in the PATH environment variable.
> /home/zx/bin/wd/wd.sh:381: command not found: getopt
> Command 'cat' is available in '/bin/cat'
> The command could not be located because '/bin' is not included in the PATH environment variable.
> wd_print_usage:2: command not found: cat

It seems something change the PATH. I also got these once when I run "wd rm docker"(after I fix the PATH).
But when I tried these commands more times, it seems not happening everytime. Sometimes it success, sometimes it fails.

I guess maybe it's because "docker" is a available command for my system? I used your tool for one or two years and it never failed. This only happens from two days ago since I decide to collect my dockerfiles to a specific directory and give it a warp point.

Environment: Linux Mint 18.3, zsh 5.1.1(x86_64-ubuntu-linux-gnu) and the newest oh-my-zsh

**Comment by mfaerevaag** [comment]
Huh, that's a bit curious.. Not really sure what could be going on here. If it has suddenly started failing now, it could have something to do with the environment, altought that doesn't narrow it down too much.

Maybe changing the calls of external commands requiring PATH to be using absolute path, e.g. changing `cat` to `/usr/bin/cat` etc., could stop it from failing. But, if something is overwriting the PATH variable, I guess it wouldn't help much.

I'll try to get back to this after Easter! Keep us updated if something changes :)

**Comment by mfaerevaag** [comment]
Does this persist? Is there any way of reproducing it?

**Comment by zxeoc** [comment]
I'm sorry I was busy these days. It seems not happening again. I'll watch on it. If it happen again, I'll let you know.

**Comment by mfaerevaag** [comment]
Sounds good. Let us know, and we'll reopen
