### ISSUE TITLE
Prezto support

### ISSUE THREAD

**Issue by EugenMayer** [mfaerevaag/wd#58]
I was using this a lot with oh my zsh but moved on to prezto - any hints on how to get this running with prezto? https://github.com/sorin-ionescu/prezto

Thanks!

**Comment by mfaerevaag** [comment]
Sorry for the late reply! I am not too familiar with prezto, but I'm definitely up for adding support for it. I'm about to hand in my thesis, so I'll try to take a look at it over the summer 👍

**Comment by rlaneyjr** [comment]
I miss WD as well.  Have a look at [here](https://www.gregjs.com/linux/2016/faster-and-more-convenient-file-system-navigation-with-wd-or-warp-dir-or-wdn/).

**Comment by mfaerevaag** [comment]
I'll get on this as soon as I find some spare time! You haven't got any good links on how to make external prezto modules? Haven't used it myself.

**Comment by mfaerevaag** [comment]
Sorry about the delay here. I do not use zsh anymore, so I probably won't do more on this. 

Help on this is very welcome!

**Comment by alpha-tango-kilo** [comment]
Taken a look at Prezto (I don't use it myself), and it doesnt look like they'd be interested in adding `wd`, as they already have equivalent tools

https://github.com/sorin-ionescu/prezto/issues/1265#issuecomment-298303601

If someone wants to open an issue there and it gets a thumbs up, I'm sure we could work it out, but I'm closing this for now
