### ISSUE TITLE
How to mv a file with a wd path?

### ISSUE THREAD

**Issue by partounian** [mfaerevaag/wd#60]
I've tried 
```
mv src/ffmpeg-concat.py $(wd path etl)/
mv: rename src/ffmpeg-concat.py to ~/go/src/github.com/partounian/etl/: No such file or directory
```
and
```
mv src/ffmpeg-concat.py $(wd path etl)/ffmpeg-concat.py
mv: rename src/ffmpeg-concat.py to ~/go/src/github.com/partounian/etl/ffmpeg-concat.py: No such file or directory
```

I then tried by copy pasting the directory above `mv src/ffmpeg-concat.py ~/go/src/github.com/partounian/etl/` and it worked

**Comment by altschuler** [comment]
Strictly speaking this is more of an issue with zsh/shells in general and has to do with abbreviated paths.

This will (obviously) work `cp foo ~/test`, but this wont `cp foo "~/test"`. However, this one _will_ work `cp foo "/home/user/test"`. That is, if the input path is a string, it must be the absolute path. 

Even if we have the absolute path in the `.warprc`, we substitute the home path with `~` here https://github.com/mfaerevaag/wd/blob/master/wd.sh#L262 and I'm not sure why?

We can either do the opposite and always return the non-abbreviated path, or we can add a flag or command to do it (such as `wd path -f <point>`). I'm not sure about backwards compatibility, I don't know if anyone would be depending on the abbreviated paths (except they look nicer), but I would lean toward always returning the full path. Would also make sense on multi user systems.

**Comment by mfaerevaag** [comment]
Nice one! Don't see any reason by the `path` command should abbreviate the output. I would better understand the `list` command, as it would make the output a bit more readable. 

As note on multi-user systems, using `sed "s:${HOME}:~:g"` for abbreviating the home directory would still work, as any path to other users' home dirs wouldn't match.

So, how about removing the abbreviation from `path` and add it to `list`?

**Comment by altschuler** [comment]
That makes sense 🎉 but we need to actively expand them I think, as a lot of people will have the abbreviated paths in their configs already. I'm sure there's some fancy zsh function for that 😜

**Comment by mfaerevaag** [comment]
Good call 👍

**Comment by partounian** [comment]
Thank you guys for looking into this! love you all

**Comment by rsteube** [comment]
There's a zsh feature called [`static named directories`](https://vincent.bernat.ch/en/blog/2015-zsh-directory-bookmarks).
I've added the following to my `.zshrc` which enables tab completion for all warp directories using the `~` prefix (e.g. `cp ~mywarpdir/subdir/myfile target`).

```
for link ($(grep -v -e '^$' ~/.warprc)) {
  folder=${link#*:}
  hash -d ${link%:*}=${folder/\~/$HOME}
}
```

**Comment by mfaerevaag** [comment]
Wow, that's very useful, thanks for the info! Should this be added as a feature, or just as a note in the README?  @altschuler

**Comment by altschuler** [comment]
That's super cool! @rsteube do you think it would make sense to add this to wd as a feature? Maybe just as a function to execute in the users own .zshrc, like `wd_enable_tab_completions_with "~"` or something like that?

**Comment by mfaerevaag** [comment]
Good idea. It would be awesome if you would be so kind as to make a PR! :tada: If you do, check out `test/tests.sh` and see that everything is working
