### ISSUE TITLE
Unknown warp point ''

### ISSUE THREAD

**Issue by NickKaramoff** [mfaerevaag/wd#65]
So I've been trying to use wd, but it doesn't seem to work at all. Whenever I try to use any command it just keeps telling me `Unknown warp point ''`. The .warprc file remains untouched.

![image](https://user-images.githubusercontent.com/6566248/53090887-b21dc880-3521-11e9-9284-fdcd2f5308e7.png)

**wd:** 0.4.6 (supplied with latest oh-my-zsh)  
**OS:** macOS 10.14.3  
**Terminal:** iTerm2

**Comment by mfaerevaag** [comment]
Hm, that's strange. Could you try deleting `.warprc` and adding a new warp point?

For instance, what's the output of the the following:
```sh
cd ~
rm ~/.warprc
wd add foo
cat ~/.warprc
wd foo
```

**Comment by NickKaramoff** [comment]
It's still the same:

![image](https://user-images.githubusercontent.com/6566248/53347470-327d6880-392a-11e9-9d6e-2b986ddb6211.png)

**Comment by NickKaramoff** [comment]
I have investigated a bit more and I have found out where the problem is. 

When iterating over command line options [the variable name `o` is chosen](https://github.com/mfaerevaag/wd/blob/master/wd.sh#L413), which happens to be one of mine zsh aliases. When I disable the alias (or rename the variable) it all works fine.

Maybe it would be wise to change the name in for loop to something more specific and less alias-worthy?

**Comment by mfaerevaag** [comment]
Aha, I see! And sorry for not following up on this...

Throughout the script, we have the convention of declaring things as local variables, preceeded with `wd_` and unseting it down in the bottom. So yes, first renaming the variable to `wd_o` and declaring it as a local a local variable could work:
```
    # parse rest of options
    local wd_o
    for wd_o
    do
        case "$wd_o"
```
and unseting it again in garbage collection:
```
## garbage collection
# if not, next time warp will pick up variables from this run
# remember, there's no sub shell

unset wd_warp
unset wd_add
# ...
unset wd_o
```
Does this fix the issue? I honestly do not remember how zsh variable scoping/shadowing work, and at this point I can't bother learning it.

A long term solution might be to refactor the code to be inside an anonymous function, like [suggested here](https://stackoverflow.com/a/13670749). But that requires some more work.

@altschuler Input?

**Comment by altschuler** [comment]
@mfaerevaag Sounds reasonable to just use the `wd_` prefix for now :)

**Comment by NickKaramoff** [comment]
> Does this fix the issue?

Strangely, it doesn't. Declaring `wd_o` as local just breaks everything as it was before.

So, this works (the name doesn't match my alias):
```zsh
for wd_o
do
    case "$wd_o"
```

But this doesn't:
```zsh
local wd_o
for wd_o
do
    case "$wd_o"
```

**Comment by NickKaramoff** [comment]
Turns out, it was all missing a semicolon

This works:
```zsh
local wd_o;
for wd_o
do
    case "$wd_o"
```

**Comment by mfaerevaag** [comment]
When trying to understand why that semicolon changes anything, I became a bit uncertain. If that `o` iterator variable in the for loop is magically defined by getopt, I'm scared of changing it. 

Also, I see that the `$o` is also used [here](https://github.com/mfaerevaag/wd/blob/master/wd.sh#L462), which also should be refactored. Not sure why the unit tests didn't catch this.

I'm currently on vacation, away from my Linux setup, so let me look at when I get back. In advance, sorry for the wait...

**Comment by NickKaramoff** [comment]
> When trying to understand why that semicolon changes anything, I became a bit uncertain.

Idk what happened to my computer back then, but right now it works both with and without a semicolon (as it should be)

> Not sure why the unit tests didn't catch this.

I think that it is because there is in fact no test that would check the `wd $POINT_NAME` (warping) functionality.
