### ISSUE TITLE
No tab completion in oh-my-zsh

### ISSUE THREAD

**Issue by ttnick** [mfaerevaag/wd#68]
I hope it is appropriate to post this as an issue. I recently installed Ubuntu 18.04, zsh and oh-my-zsh. Upgrading from 14.04 would have been hopeless for various reasons. However, while `wd` worked smoothly on my old system including tab completion for warp points. On my new system (basically vanilla including the `.zshrc`), tab completion seems to be broken, since I only get compeltion for files/directories of the current directory not for warp points.

Do you have any clue what is missing? The only changes I made so far were to add wd to plugins and adjusted the `$PATH`, so it is really odd to me why this is not working on my machine.

**Comment by gutuva** [comment]
Same here in Arch.

**Comment by altschuler** [comment]
Strange, can you see if zsh ever calls this function? https://github.com/mfaerevaag/wd/blob/303e68fe0104cc4ab780afae9d904b3787fd68a0/_wd.sh#L10

**Comment by ttnick** [comment]
I just put an `echo "zsh is here\n"` at the beginning of `_wd()` and then called `source .oh-my-zsh/plugins/wd/_wd.sh`. The output then is:
```
zsh is here

_arguments:comparguments:319: can only be called from completion function
```
Might be worth noting that if I restart my terminal this `echo` is not executed, probably should have(?).

**Comment by eXaminator** [comment]
I have the exact same problem and error as @ttnick

Any chance for someone who understands zsh autocompletion scripts to look into this?

**Comment by eXaminator** [comment]
I managed to get this fixed. This was due to me using the default zsh installation on mac, which obviously is pretty old.

After installing the latest zsh and zsh-completions versions this works like a charm!

**Comment by mfaerevaag** [comment]
Great! As we have been completely clueless on these completion bugs, it would be a relief if this was the cause. @ttnick Can you confirm?

**Comment by ttnick** [comment]
Unfortunately not :( `zsh` is now version 5.7.1 (latest) but auto-complete still does not work.

**Comment by ttnick** [comment]
After I encountered the same issue on a different machine with a different OS, I started digging again. Turns out that the fix is already mentioned in the `README`, i.e. `rm .zcompdump*`. I have not recognized it since this section started with `If you're NOT using [oh-my-zsh]`, but this (+ restarting the shell) was all that it takes to make auto-completion work.

I finally will sleep better this night, I hope so do you! :D

**Comment by mfaerevaag** [comment]
Awesome, good to hear!
