### ISSUE TITLE
cli help doesn't show how to simply warp

### ISSUE THREAD

**Issue by towc** [mfaerevaag/wd#71]
I now love using `wd`, but I remember being confused by what it did when I just typed `wd` the first time.

I think having adding text similar to this would help:
```
<point>          Warps to point
<point> <path>   Waps to point and `cd`s to path
```

Would also publicize a workaround for https://github.com/mfaerevaag/wd/issues/66

**Comment by mfaerevaag** [comment]
Fixed by your [PR#72](https://github.com/mfaerevaag/wd/pull/72) 🥇
