### ISSUE TITLE
wd <point> keeps listing all warp points

### ISSUE THREAD

**Issue by cor** [mfaerevaag/wd#74]
## Expected behavior:
When running `wd <point>`, wd warps to the specified directory _without listing all warp points_

## Actual behavior
When running `wd <point>`, wd _prints out a list of all warp points_ and then warps to the specified directory.

**Comment by mfaerevaag** [comment]
Thanks for reporting!

Could you please share your zsh and wd version? Also, it may have something to do with autocompletion, as `wd <tab>` lists warp points. So try `rm -f ~/.zcompdump; compinit` to rebuild the autocompletion monster in zsh

**Comment by cor** [comment]
Interestingly, running `wd --version` appears to log the entire source code of wd, without actually noting the wd version. My zsh version is `zsh 5.7.1 (x86_64-apple-darwin19.0)`

**Comment by mfaerevaag** [comment]
That's quite strange, indeed. Has anything changed? Not sure where to start here..

**Comment by cor** [comment]
Nothing has changed. It is indeed very strange and I’m not sure how I could provide reproduction instructions

**Comment by cor** [comment]
Reinstalling `wd` appears to fix it. Thanks for helping me, @mfaerevaag!
