### ISSUE TITLE
WD_CONFIG in .zshrc has no effect

### ISSUE THREAD

**Issue by Acidham** [mfaerevaag/wd#75]
I tried to define custom location for `.warprc` . I added the following line to `.zshrc`:
`export WD_CONFIG=~/Library/Mobile\ Documents/com~apple~CloudDocs/.config/.warprc`
but it has no effect.

wd version 0.4.6

**Comment by mfaerevaag** [comment]
Thanks for reporting! Could you please share your zsh and wd version?

**Comment by Acidham** [comment]
* wd version 0.4.6 taken from oh_my_zsh 
* zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by mfaerevaag** [comment]
Could you try doing a checkout of master and see if the problem persists? Been some time since a new release has been made, so there's quite a few commits since 0.4.6

**Comment by Acidham** [comment]
After updating wd.sh from master I am experiencing a strange behavior.
1. I configured in wd: la → ~/Library/LaunchAgents 
2. I type wd la and wd jumps into the directory as configured above
3. my zsh prompt changes to shortcut "la" see below.

**~/Library/LaunchAgents**
▶ wd la

**~la**
▶ la
total 56

**Comment by AtkLordOverAll** [comment]
Same thing happens to me, I use P10k to see my current directory (my full config is available in my dots repository to replicate).
If I'm in a directory that has a warp-point, I see `~warpname` instead of the path. This persists if you navigate to subdirectories within the warp directory too, e.g. `~warpname/src`.
If this behaviour could be made optional that'd be great.

**Comment by lucizek** [comment]
I do completely agree. Option to opt-out of this feature is a must - same as many others I do use very shortcut-y names for projects and don't want to see any of that instead of that proper folder name.

**Comment by mfaerevaag** [comment]
The thing with the prompt being replaced is, from my understanding, a bug caused by a change to ohmyzsh and handled in https://github.com/mfaerevaag/wd/issues/85.

The `WD_CONFIG` thing, though, is still a mystery to me. @alpha-tango-kilo Were you able to reproduce this?

**Comment by alpha-tango-kilo** [comment]
@Acidham are you still experiencing this issue?

Going to close this issue unless we hear from you in a few days

**Comment by Acidham** [comment]
fixed ...thank for the heads up!
