### ISSUE TITLE
Shell prints ~ before directory after warping

### ISSUE THREAD

**Issue by ttnick** [mfaerevaag/wd#85]
Hi,

after the last ohmyzsh update whenever I warp into a directory, its name gets displayed wrong. Usually, when I type `wd foobar` my shell prompts `-> foobar` now it does ` -> ~foobar` and it remains like this for the entire session. However, i do not experience this, when I just `cd` into the directory.

It might very well be the case that the issue is rather inside ohmyzsh and not in the plugin.

Apart from the plugins wd, git and colored-man-pages I use a vanilla ohmyzsh, so unless there is something really strange going on, this should be easy to reproduce but I could not find ny fix so far.

I would appreciate any help, this is really triggering my OCD. :grin:

**Comment by alpha-tango-kilo** [comment]
Sounds similar to #75, though seems strange that you don't get the issue when you just `cd` into the directory normally. For my prompt it always displays `~warpname` if I'm in a directory that has a warp point associated.

Vanilla zsh with zsh-syntax-highlightning, p10k, and wd

**Comment by jessemutz** [comment]
> after the last ohmyzsh update whenever I warp into a directory, its name gets displayed wrong. Usually, when I type `wd foobar` my shell prompts `-> foobar` now it does ` -> ~foobar` and it remains like this for the entire session. However, i do not experience this, when I just `cd` into the directory.

Same here. If I have a warp point named "bz" for `~/foo/bar/baz`, `$ cd` will give me `~/foo/bar/baz`, whereas `$ wd bz` will propmt `~bz`, which is the name of the warp point.

**Comment by gscalise** [comment]
Add `WD_SKIP_EXPORT=true` to your `.zshrc` file to fix this issue.

**Comment by ttnick** [comment]
This works! Thanks!

**Comment by mfaerevaag** [comment]
Is there any way we can get around this without having to add `WD_SKIP_EXPORT=true` when using ohmyzsh?

I haven't used ohmyzsh, or zsh for that matter, for a couple of years now so I'm a bit rusty :fearful:

**Comment by alpha-tango-kilo** [comment]
Yeah this isnt even ohmyzsh specific, I install everything manually and my P10k prompt still has this issue. 

What does the `hash` command even do? It's not one I've come across before as it's a zsh feature AFAIK

We could maybe have this off by default? I dont know what it does but I haven't noticed a difference in my usage of `wd` honestly

**Comment by mfaerevaag** [comment]
Agreed! If anyone gets the time a PR would be much appreciated :heart: If not, I'll try to find some during one of the following weekends.

**Comment by alpha-tango-kilo** [comment]
Assign me the issue, I can get to it, shouldn't be hard.

Rename the variable to `WD_EXPORT` so then it's unset (meaning this issue doesn't occur) by default, what do you reckon?
