### ISSUE TITLE
Test suite does not support being run in a path with spaces

### ISSUE THREAD

**Issue by alpha-tango-kilo** [mfaerevaag/wd#89]
In the tests very few variables are quoted `"$foo"` instead of `$foo`, meaning everything goes wild if there's a space in the full path to the tests directory.

Shall probably make a PR for this at some point

**Comment by mfaerevaag** [comment]
Very good point!

**Comment by alpha-tango-kilo** [comment]
I'm working on a resolution for this on my fork, PR will come through somewhen if no one else touches it in the mean time
