### ISSUE TITLE
feature request: a way to print absolute paths

### ISSUE THREAD

**Issue by MatrixManAtYrService** [mfaerevaag/wd#91]
Hi, wd is awesome, thanks for maintaining it!

I want to do this:

    python  $(wd path someplace)/somescript.py

But since `wd` prints paths anchored at my home directory (i.e. with a leading ~)  I get errors like:

        python: can't open file '~/path/to/someplace/somescript.py': [Errno 2] No such file or directory

As a workaround I've added

    wdp() {
        WARP_POINT="$(wd path $*)"
        eval "echo $WARP_POINT"
    }

So I can do:

    python  $(wdp someplace)/somescript.py

But it would be cool if it were built in.

**Comment by mfaerevaag** [comment]
Aha, weird that python doesn't understand anchored paths. I don't have anything against changing the `wd path` command to use absolute path. Let's see if anybody else disagrees.

**Comment by alpha-tango-kilo** [comment]
I agree that this makes sense - works better in scripts and is no less usable in any way really. I like the idea and could probably implement it at some point
