### ISSUE TITLE
Idea: Collaborators overview in README

### ISSUE THREAD

**Issue by mfaerevaag** [mfaerevaag/wd#98]
**Is your feature request related to a problem? Please describe.**
We should give credits to the contributors! As I have given the maintainer role away, this has become even more important, as to reflect who's actually doing the work :1st_place_medal: 

**Describe the solution you'd like**
Adding a section to the README headlined with "Contributors" seems to be a common way in the open source community.

**Describe alternatives you've considered**
- This can be done manually (writing markup with lists of the contributors), where you can prioritize active maintainers. 
- Or, automatically, by using a tool such as [all-contributors](https://github.com/all-contributors/all-contributors), which I do not have any experience with.

**Additional context**
Github has recently introduced the "Contributors" section to the right sidebar of a repo's mainview:
![image](https://user-images.githubusercontent.com/1221244/92363974-a3dad180-f0f2-11ea-9952-2c60f10d0552.png)

Perhaps this is sufficient for "Contributors", but it does not reflect who's the maintainers, which are currently @alpha-tango-kilo and @MattLewin . Therefore, maybe the best solution would be to have an overview of the maintainers, and let Github do the overview of the rest?

Comments are welcome!

**Comment by alpha-tango-kilo** [comment]
I think stating who the maintainers are in the README is a solid idea, I'll add that in at some point.

As for the rest of contributions I think GitHub's built in thing you've highlighted is good, plus like with the release notes for v0.5.0 I gave credits to anyone who contributed to something in the changelog, so I think that's a fair system to credit those lovely people who submit PRs

**Comment by mfaerevaag** [comment]
Cool! Yeah, really like that release :100: :100:

**Comment by alpha-tango-kilo** [comment]
Thought it was about time 😎

**Comment by alpha-tango-kilo** [comment]
Added maintainers section
