### ISSUE TITLE
Migrating to travis-ci.com from travis-ci.org

### ISSUE THREAD

**Issue by alpha-tango-kilo** [mfaerevaag/wd#99]
Currently this repo uses Travis CI for testing, however following a [recent announcement email](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=b2d1739a52), they're going to be moving from a .org domain to a .com, requiring manual intervention for repository owners.

@mfaerevaag can you take a look at this and see if anything needs doing please?

You can see the documentation for the migration process [here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository)

**Comment by mfaerevaag** [comment]
Sure, I'll handle it :+1: Perhaps moving to Github Actions could be nice, which wasn't available when I first set it up. Any preferences?

**Comment by alpha-tango-kilo** [comment]
I'd prefer Travis personally as it's not GitHub/Microsoft dependent, but either works

**Comment by mfaerevaag** [comment]
Seems like something is working: https://travis-ci.com/github/mfaerevaag/wd/builds/204671650

Maybe just change the URL of the badge in the README then?
